name: Release
on:
  push:
    branches:
      - main
      - alpha
      - beta
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency: 
      group: deploy-${{github.ref}}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: "https://registry.npmjs.org"
          cache: 'npm'
      - uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{runner.os}}-node-${{hashFiles('package-lock.json')}}
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - run: AUTOREL_DEBUG=1 ./bin/cli.js --publish
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        
